# ============================================================
# ALLUCO
# Configuration unique
# ============================================================

ALLUCO_ADMIN_USERNAME = "Mahdi"
ALLUCO_ADMIN_PASSWORD = "Mahdi123++"

SUPABASE_URL = "https://bsqwvnjlauwnpdqcoedb.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_HtmM8e4yt6tfY-kMqihTuA_r5OdxrC1"


[data]

# Exemple même dossier que app.py
source_file = "extraction_ax.xlsx"

# Si votre nouveau fichier est dans un dossier data :
# source_file = "data/extraction_ax.xlsx"


[planning]

year = 2026
week = 38

capacity_weekday_h = 16.0
minutes_per_bal = 4.0
powder_coeff = 0.052
cleaning_min = 15
target_utilization = 0.94
solver_seconds = 18.0

auto_generate = true
allow_relaquage = false

max_jobs = 1600
pool_factor = 2.7

max_colors_per_day = 4
include_without_of = false
forbid_white_black_adjacent = true


[ui]

timezone = "Africa/Tunis"
